May 2021 Update
microsoft/MCW-Cloud-native-applications pull request #249
Opened 2021-05-07 21:55 UTC by hatboyzero

Please review. Closes #247

2021-05-17 19:03 UTC, sabbour requested changes

2021-05-17 19:03 UTC, sabbour commented on Hands-on lab/HOL step-by-step - Cloud-native applications.md
> +  - [Prerequisites](#prerequisites)
Should the prerequisites include a reference to complete the "Before the HOL" section? I don't see this mentioned except in the "Requirements" section as a passing reference that's not linked, and only to validate the subscription core quota.

2021-05-20 15:54 UTC, camsipes19 commented on Hands-on lab/Before the HOL - Cloud-native applications.md
> +
Are any of the requirements or before the hands-on-lab steps different or not applicable if someone is going through the lab within a Spektra Cloud Labs enviornment? For example in the requirements, are the notes of Azure subscription, Azure AD tenant membership, etc. applicable? For example in before the HOL, would the Azure Cloud Shell already be preconfigured?

2021-05-20 15:56 UTC, camsipes19 commented on Hands-on lab/Before the HOL - Cloud-native applications.md
>  Information in this document, including URL and other Internet Web site references, is subject to change without notice. Unless otherwise noted, the example companies, organizations, products, domain
Adding to Ahmed's comment, when the lab is consumed through a Spektra Cloud Lab enviornment, can any of the before the lab steps be preconfigured? If so, we should also identify which of those steps are not applicable 'if you are taking this lab in a preconfigured enviornment' (or similar verbiage)

2021-05-20 15:57 UTC, camsipes19 commented on Hands-on lab/Before the HOL - Cloud-native applications.md
> +1. From Azure Cloud Shell, connect to your buidl agent if you are not already connected.
Build is misspelled in "connect to your buidl agent if you are..."

2021-05-20 16:01 UTC, camsipes19 commented on Hands-on lab/Before the HOL - Cloud-native applications.md
> +19. If you received a JSON response to the /speakers content request and an HTML response from the web application, your environment is working as expected.
Is it possible to include an example of what "receiving a JSON response to the /speakers content request" should look like as that is the experience in the other steps above where there is a step to check configuration followed by an example of what that check should look like (e.g. step 8, step 12)

2021-05-20 16:10 UTC, camsipes19 commented on Hands-on lab/HOL step-by-step - Cloud-native applications.md
>    - [Requirements](#requirements)
Same comment in this requirements section for the step by step that I left in the requirements section of the before the lab ... are any of the requirements different or not applicable if someone is going through the lab within a Spektra Cloud Labs enviornment? For example, are the notes of Azure subscription, Azure AD tenant membership, etc. applicable? Will "other tools" still need to be installed or will those tools preexist?

2021-05-20 16:13 UTC, camsipes19 commented on Hands-on lab/HOL step-by-step - Cloud-native applications.md
>    - [Overview](#overview)
In the first paragraph in the overview section, it feels like we're missing an opportunity to explain why AKS is being used here and the unique value the service provides wrt deploying containers in a dynamically load-balanced manner, scaling them on demand, etc. Would love to see something like "... critical aspects of the hosting enviornment. They will be deploying their applications to Azure Kubernetes Service <because of XYZ reason(s)>. Further, FabMedical wants to learn how to..."

2021-05-20 16:20 UTC, camsipes19 commented on Hands-on lab/HOL step-by-step - Cloud-native applications.md
> +  - [Exercise 1: Migrate MongoDB to Cosmos DB using Azure Database Migration Service](#exercise-1-migrate-mongodb-to-cosmos-db-using-azure-database-migration-service)
I may have missed it, but I don't believe we set up why MongoDB to CosmosDB is the focus here. Might be worth adding something like "for the purposes of this lab MongoDB and CosmosDB will be the database services of focus, however, other DB services like XYZ would also support a containerized application architecture running on AKS"

The objective wouldn't be to explain the pros/cons of the different DBs, simply acknowledge that others would be applicable here, but Cosmos is the preferred option thus the one this lab will focus on.

2021-05-20 16:30 UTC, camsipes19 commented on Hands-on lab/HOL step-by-step - Cloud-native applications.md
In description of Task #3 (line 763) would be good to add details on why we're setting up autoscale on Cosmos DB and what value that provides in the context of FabMedical. I really like how this is done in the other tasks (e.g., task 1 in exercise 4, task 2 in exercise 3) as it enhances the learning quite a bit, IMO

2021-05-20 16:32 UTC, camsipes19 commented on Hands-on lab/HOL step-by-step - Cloud-native applications.md
>    - [Abstract and learning objectives](#abstract-and-learning-objectives)
Can we elaborate on which "common DevOps procedures" will be performed? When going through the lab they didn't immediately jump out at me.

2021-05-20 16:34 UTC, camsipes19 commented
Completed my review. Great work, team!

2021-05-20 16:46 UTC, hatboyzero commented on Hands-on lab/Before the HOL - Cloud-native applications.md
> +
I would say nothing, but I have zero insight into how Spektra creates their cloud environment, so I don't really know.

2021-05-25 19:51 UTC, merged